"""CLI and compatibility facade for the LEGO Technic gamepad bridge."""

from __future__ import annotations

import argparse
import asyncio

from bridge.audio import (
    AudioObjectPropertyAddress,
    CoreAudioOutputDevice,
    MacAfplayBeepPlayer,
    ReverseBeep,
    audio_output_devices,
    coreaudio,
    coreaudio_default_output_device,
    coreaudio_has_output_streams,
    coreaudio_output_devices,
    coreaudio_property,
    coreaudio_set_default_output_device,
    coreaudio_status_ok,
    coreaudio_string_property,
    corefoundation,
    dualsense_audio_device,
    four_char_code,
    log_message,
    open_pygame_sound,
    open_system_sound,
    reverse_beep_status,
    run_audio_probe,
    select_dualsense_audio_device,
    select_dualsense_coreaudio_device,
    select_forced_coreaudio_device,
)
from bridge.controller import (
    axis_to_percent,
    button_held,
    gamepad_name_is_dualsense,
    gamepad_was_disconnected,
    init_gamepad,
    read_drive_input,
    read_drive_state,
    read_throttle,
    read_trigger_pressures,
    run_probe,
    snapshot,
    trigger_amount,
    try_init_gamepad,
)
from bridge.dashboard import (
    CarTelemetry,
    LiveConsole,
    SetupConsole,
    boost_status_label,
    car_light_beams,
    clip_terminal_line,
    dashboard_bar,
    dashboard_bool,
    dashboard_button,
    dashboard_center_bar,
    dashboard_direction,
    dashboard_off_color,
    dashboard_panel_line,
    dashboard_percent,
    dashboard_steering,
    render_car_dashboard,
    render_setup_panel,
    speed_mode_selector,
    telemetry_fraction,
)
from bridge.feedback import (
    BoostRumble,
    BoostUnavailableFeedback,
    ControllerLed,
    CrashLockout,
    boost_feedback_active,
    boost_led_color,
    boost_led_feedback_active,
    boost_rumble_feedback_at,
    boost_rumble_strength,
    change_speed_mode_with_feedback,
    configure_sdl_controller_led,
    decrease_speed_mode,
    default_led_color,
    drive_power_for_trigger,
    drive_rumble_strength,
    gamepad_led_color,
    increase_speed_mode,
    led_color_label,
    load_sdl,
    reverse_led_color,
    rumble_once,
    rumble_speed_change,
    sdl_library_candidates,
    stop_rumble,
    update_gamepad_led,
)
from bridge.lighting import AttackSignal, AutomaticLights
from bridge.low_level_control import LowLevelControl
from bridge.paths import PORT_MAP_PATH, REVERSE_BEEP_PATH
from bridge.platform import configure_process_for_platform
from bridge.port_map import load_port_map, port_id
from bridge.profiles import GamepadProfile, ModelProfile
from bridge.safety import SafetyLimits, require_user_acknowledgement
from bridge.session import (
    ConnectedHardware,
    load_port_map_for_drive,
    required_hub_port_issue,
    run_control,
    run_live_session,
    safe_shutdown,
    startup_steps,
    wait_for_dualsense,
    wait_for_gamepad,
    wait_for_hub,
)
from bridge.settings import (
    ATTACK_SIGNAL_DURATION_S,
    AXIS_REPORT_STEP,
    BOOST_FEEDBACK_DELAY_S,
    BOOST_LED_COLOR,
    BOOST_LED_DIM_COLOR,
    BOOST_LED_TAIL_S,
    BOOST_RUMBLE_FEEDBACK_DELAY_S,
    BOOST_RUMBLE_REFRESH_MS,
    BOOST_RUMBLE_STRENGTH,
    BOOST_UNAVAILABLE_LED_COLOR,
    BOOST_UNAVAILABLE_LED_FLASH_INTERVAL_S,
    BOOST_UNAVAILABLE_LED_FLASH_S,
    BOOST_UNAVAILABLE_RUMBLE_MS,
    CORE_AUDIO_PATH,
    CORE_FOUNDATION_PATH,
    CRASH_LED_COLOR,
    CRASH_LOCKOUT_S,
    CRASH_RUMBLE_STRENGTH,
    CRASH_SPEED_THRESHOLD_RATIO,
    DASHBOARD_DISABLE_ENV,
    DASHBOARD_ELLIPSIS_WIDTH,
    DASHBOARD_LOG_LIMIT,
    DASHBOARD_MAX_WIDTH,
    DEFAULT_SPEED_MODE,
    DRIVE_RUMBLE_MAX_STRENGTH,
    DRIVE_RUMBLE_PRESSURE_EXPONENT,
    DUALSENSE_AUDIO_DEVICE_ENV,
    DUALSENSE_AUDIO_DEVICE_HINTS,
    DUALSENSE_GAMEPAD_HINTS,
    FRONT_LIGHTS_OFF_DELAY_S,
    LED_OFF_COLOR,
    LOOP_INTERVAL_S,
    NON_DUALSENSE_GAMEPAD_HINTS,
    RECONNECT_DUALSENSE,
    RECONNECT_HUB,
    REVERSE_BEEP_OUTPUT_ENV,
    REVERSE_BEEP_START_DELAY_S,
    REVERSE_LED_PHASE_S,
    RGB,
    ROCKET_LIGHTS_BLINK_INTERVAL_S,
    SDL_INIT_GAMECONTROLLER,
    SESSION_EXIT,
    SPEED_MODE_1,
    SPEED_MODE_2,
    SPEED_MODE_3,
    SPEED_MODE_LED_COLORS,
    SPEED_MODE_RATIOS,
    SPEED_MODE_SEQUENCE,
    SPEED_RUMBLE_DURATION_MS,
    SPEED_RUMBLE_STRENGTH,
    STARTUP_RETRY_DELAY_S,
)
from bridge.transport import TechnicMoveHub

__all__ = [
    "ATTACK_SIGNAL_DURATION_S",
    "AXIS_REPORT_STEP",
    "BOOST_FEEDBACK_DELAY_S",
    "BOOST_LED_COLOR",
    "BOOST_LED_DIM_COLOR",
    "BOOST_LED_TAIL_S",
    "BOOST_RUMBLE_FEEDBACK_DELAY_S",
    "BOOST_RUMBLE_REFRESH_MS",
    "BOOST_RUMBLE_STRENGTH",
    "BOOST_UNAVAILABLE_LED_COLOR",
    "BOOST_UNAVAILABLE_LED_FLASH_INTERVAL_S",
    "BOOST_UNAVAILABLE_LED_FLASH_S",
    "BOOST_UNAVAILABLE_RUMBLE_MS",
    "CORE_AUDIO_PATH",
    "CORE_FOUNDATION_PATH",
    "CRASH_LED_COLOR",
    "CRASH_LOCKOUT_S",
    "CRASH_RUMBLE_STRENGTH",
    "CRASH_SPEED_THRESHOLD_RATIO",
    "DASHBOARD_DISABLE_ENV",
    "DASHBOARD_ELLIPSIS_WIDTH",
    "DASHBOARD_LOG_LIMIT",
    "DASHBOARD_MAX_WIDTH",
    "DEFAULT_SPEED_MODE",
    "DRIVE_RUMBLE_MAX_STRENGTH",
    "DRIVE_RUMBLE_PRESSURE_EXPONENT",
    "DUALSENSE_AUDIO_DEVICE_ENV",
    "DUALSENSE_AUDIO_DEVICE_HINTS",
    "DUALSENSE_GAMEPAD_HINTS",
    "FRONT_LIGHTS_OFF_DELAY_S",
    "LED_OFF_COLOR",
    "LOOP_INTERVAL_S",
    "NON_DUALSENSE_GAMEPAD_HINTS",
    "PORT_MAP_PATH",
    "RECONNECT_DUALSENSE",
    "RECONNECT_HUB",
    "REVERSE_BEEP_OUTPUT_ENV",
    "REVERSE_BEEP_PATH",
    "REVERSE_BEEP_START_DELAY_S",
    "REVERSE_LED_PHASE_S",
    "RGB",
    "ROCKET_LIGHTS_BLINK_INTERVAL_S",
    "SDL_INIT_GAMECONTROLLER",
    "SESSION_EXIT",
    "SPEED_MODE_1",
    "SPEED_MODE_2",
    "SPEED_MODE_3",
    "SPEED_MODE_LED_COLORS",
    "SPEED_MODE_RATIOS",
    "SPEED_MODE_SEQUENCE",
    "SPEED_RUMBLE_DURATION_MS",
    "SPEED_RUMBLE_STRENGTH",
    "STARTUP_RETRY_DELAY_S",
    "AttackSignal",
    "AudioObjectPropertyAddress",
    "AutomaticLights",
    "BoostRumble",
    "BoostUnavailableFeedback",
    "CarTelemetry",
    "ConnectedHardware",
    "ControllerLed",
    "CoreAudioOutputDevice",
    "CrashLockout",
    "GamepadProfile",
    "LiveConsole",
    "LowLevelControl",
    "MacAfplayBeepPlayer",
    "ModelProfile",
    "ReverseBeep",
    "SafetyLimits",
    "SetupConsole",
    "TechnicMoveHub",
    "audio_output_devices",
    "axis_to_percent",
    "boost_feedback_active",
    "boost_led_color",
    "boost_led_feedback_active",
    "boost_rumble_feedback_at",
    "boost_rumble_strength",
    "boost_status_label",
    "button_held",
    "car_light_beams",
    "change_speed_mode_with_feedback",
    "clip_terminal_line",
    "configure_process_for_platform",
    "configure_sdl_controller_led",
    "coreaudio",
    "coreaudio_default_output_device",
    "coreaudio_has_output_streams",
    "coreaudio_output_devices",
    "coreaudio_property",
    "coreaudio_set_default_output_device",
    "coreaudio_status_ok",
    "coreaudio_string_property",
    "corefoundation",
    "dashboard_bar",
    "dashboard_bool",
    "dashboard_button",
    "dashboard_center_bar",
    "dashboard_direction",
    "dashboard_off_color",
    "dashboard_panel_line",
    "dashboard_percent",
    "dashboard_steering",
    "decrease_speed_mode",
    "default_led_color",
    "drive_power_for_trigger",
    "drive_rumble_strength",
    "dualsense_audio_device",
    "four_char_code",
    "gamepad_led_color",
    "gamepad_name_is_dualsense",
    "gamepad_was_disconnected",
    "increase_speed_mode",
    "init_gamepad",
    "led_color_label",
    "load_port_map",
    "load_port_map_for_drive",
    "load_sdl",
    "log_message",
    "main",
    "open_pygame_sound",
    "open_system_sound",
    "port_id",
    "read_drive_input",
    "read_drive_state",
    "read_throttle",
    "read_trigger_pressures",
    "render_car_dashboard",
    "render_setup_panel",
    "require_user_acknowledgement",
    "required_hub_port_issue",
    "reverse_beep_status",
    "reverse_led_color",
    "rumble_once",
    "rumble_speed_change",
    "run_audio_probe",
    "run_control",
    "run_live_session",
    "run_probe",
    "safe_shutdown",
    "sdl_library_candidates",
    "select_dualsense_audio_device",
    "select_dualsense_coreaudio_device",
    "select_forced_coreaudio_device",
    "snapshot",
    "speed_mode_selector",
    "startup_steps",
    "stop_rumble",
    "telemetry_fraction",
    "trigger_amount",
    "try_init_gamepad",
    "update_gamepad_led",
    "wait_for_dualsense",
    "wait_for_gamepad",
    "wait_for_hub",
]


async def main() -> None:
    """Parse CLI arguments and dispatch the requested bridge mode."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--arm", action="store_true", help="Live control with hub")
    parser.add_argument("--probe", action="store_true", help="Log gamepad axes/buttons without connecting to the hub")
    parser.add_argument(
        "--audio-devices",
        action="store_true",
        help="List audio outputs and selected reverse beep device",
    )
    parser.add_argument("--model", default="tumbler", help="Model profile in config/models/")
    parser.add_argument("--gamepad", default="dualsense", help="Gamepad profile in config/gamepads/")
    args = parser.parse_args()

    if args.audio_devices:
        run_audio_probe()
        return

    if args.probe:
        setup = SetupConsole()
        pad = GamepadProfile.load(args.gamepad)
        pygame_mod, joystick = await wait_for_gamepad(setup, pad)
        setup.stop()
        run_probe(pygame_mod, joystick)
        return

    if not args.arm:
        parser.print_help()
        return

    await run_control(args.model, args.gamepad)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nExited.")
