"""Gamepad adapters, profiles, discovery, and normalized input helpers."""

from . import dualsense, generic_sdl, steamdeck_gamepad
from .input import (
    SdlGameControllerJoystick,
    axis_to_percent,
    button_held,
    call_or_unknown,
    gamepad_diagnostic_lines,
    gamepad_diagnostics,
    gamepad_name_is_dualsense,
    gamepad_was_disconnected,
    init_gamepad,
    init_sdl_game_controller,
    poll_controller_events,
    read_drive_input,
    read_drive_state,
    read_throttle,
    read_trigger_pressures,
    refresh_joystick_subsystem,
    run_probe,
    sdl2_controller_module,
    sdl_controller_diagnostic_lines,
    snapshot,
    trigger_amount,
    try_init_gamepad,
)
from .profile_loader import AUTO_GAMEPAD_CANDIDATES, AUTO_GAMEPAD_PROFILE, GamepadProfile, gamepad_profile_candidates

__all__ = [
    "AUTO_GAMEPAD_CANDIDATES",
    "AUTO_GAMEPAD_PROFILE",
    "GamepadProfile",
    "SdlGameControllerJoystick",
    "axis_to_percent",
    "button_held",
    "call_or_unknown",
    "dualsense",
    "gamepad_diagnostic_lines",
    "gamepad_diagnostics",
    "gamepad_name_is_dualsense",
    "gamepad_profile_candidates",
    "gamepad_was_disconnected",
    "generic_sdl",
    "init_gamepad",
    "init_sdl_game_controller",
    "poll_controller_events",
    "read_drive_input",
    "read_drive_state",
    "read_throttle",
    "read_trigger_pressures",
    "refresh_joystick_subsystem",
    "run_probe",
    "sdl2_controller_module",
    "sdl_controller_diagnostic_lines",
    "snapshot",
    "steamdeck_gamepad",
    "trigger_amount",
    "try_init_gamepad",
]
