"""Shared runtime constants for the gamepad bridge."""

from __future__ import annotations

from . import paths

REVERSE_BEEP_PATH = paths.REVERSE_BEEP_PATH

LOOP_INTERVAL_S = 0.05
AXIS_REPORT_STEP = 0.05

FRONT_LIGHTS_OFF_DELAY_S = 1.0
ROCKET_LIGHTS_BLINK_INTERVAL_S = 1.0
ATTACK_SIGNAL_DURATION_S = 1.0
REVERSE_LED_PHASE_S = 1.0
REVERSE_BEEP_START_DELAY_S = 1.0

SPEED_RUMBLE_DURATION_MS = 120
SPEED_RUMBLE_STRENGTH = 0.65
DRIVE_RUMBLE_MAX_STRENGTH = 0.7
DRIVE_RUMBLE_PRESSURE_EXPONENT = 1.4

BOOST_FEEDBACK_DELAY_S = 0.2
BOOST_RUMBLE_FEEDBACK_DELAY_S = 0.65
BOOST_LED_TAIL_S = 0.5
BOOST_RUMBLE_REFRESH_MS = 200
BOOST_RUMBLE_STRENGTH = 1.0
BOOST_UNAVAILABLE_RUMBLE_MS = 140
BOOST_UNAVAILABLE_LED_FLASH_S = 0.6
BOOST_UNAVAILABLE_LED_FLASH_INTERVAL_S = 0.1
CRASH_SPEED_THRESHOLD_RATIO = 0.30
CRASH_LOCKOUT_S = 3.0
CRASH_RUMBLE_STRENGTH = 1.0

SPEED_MODE_1 = 1
SPEED_MODE_2 = 2
SPEED_MODE_3 = 3
SPEED_MODE_SEQUENCE = (SPEED_MODE_1, SPEED_MODE_2, SPEED_MODE_3)
DEFAULT_SPEED_MODE = SPEED_MODE_1
SPEED_MODE_RATIOS = {
    SPEED_MODE_1: 0.25,
    SPEED_MODE_2: 0.5,
    SPEED_MODE_3: 1.0,
}
SPEED_MODE_LED_COLORS = {
    SPEED_MODE_1: (48, 48, 48),
    SPEED_MODE_2: (140, 140, 140),
    SPEED_MODE_3: (255, 255, 255),
}

BOOST_LED_COLOR = (255, 96, 0)
BOOST_LED_DIM_COLOR = (72, 24, 0)
BOOST_UNAVAILABLE_LED_COLOR = (255, 0, 0)
CRASH_LED_COLOR = (255, 0, 0)
LED_OFF_COLOR = (0, 0, 0)

SDL_INIT_GAMECONTROLLER = 0x00002000
RGB = tuple[int, int, int]

DUALSENSE_AUDIO_DEVICE_ENV = "DUALSENSE_AUDIO_DEVICE"
REVERSE_BEEP_OUTPUT_ENV = "REVERSE_BEEP_OUTPUT"
DUALSENSE_AUDIO_DEVICE_HINTS = ("dualsense", "wireless controller")
CORE_AUDIO_PATH = "/System/Library/Frameworks/CoreAudio.framework/CoreAudio"
CORE_FOUNDATION_PATH = "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation"

DASHBOARD_DISABLE_ENV = "CAR_DASHBOARD"
DASHBOARD_LOG_LIMIT = 120
DASHBOARD_MAX_WIDTH = 110
DASHBOARD_ELLIPSIS_WIDTH = 3

STARTUP_RETRY_DELAY_S = 2.0
DUALSENSE_GAMEPAD_HINTS = ("dualsense", "wireless controller", "ps5")
NON_DUALSENSE_GAMEPAD_HINTS = ("xbox",)

RECONNECT_DUALSENSE = "dualsense"
RECONNECT_HUB = "hub"
SESSION_EXIT = "exit"
